/* Auto-generated by scripts/build-dsa-data.mjs — topics & counts from roadmap PDF */
const DSA_ROADMAP = [
  {
    "id": "arrays",
    "topic": "Arrays",
    "topicColor": "#ffa116",
    "problems": [
      {
        "title": "Find the largest element in an array",
        "url": "https://www.geeksforgeeks.org/problems/largest-element--gfg--382--1/1",
        "difficulty": "easy"
      },
      {
        "title": "Find the second largest element",
        "url": "https://www.geeksforgeeks.org/problems/second-largest--gfg--375--1/1",
        "difficulty": "easy"
      },
      {
        "title": "Check if array is sorted",
        "url": "https://www.geeksforgeeks.org/problems/check-if-an-array-is-sorted-or-not--gfg--1/1",
        "difficulty": "easy"
      },
      {
        "title": "Find missing number in array",
        "url": "https://leetcode.com/problems/missing-number/",
        "difficulty": "easy"
      },
      {
        "title": "Remove duplicates from sorted array",
        "url": "https://leetcode.com/problems/remove-duplicates-from-sorted-array/",
        "difficulty": "easy"
      },
      {
        "title": "Rotate array",
        "url": "https://leetcode.com/problems/rotate-array/",
        "difficulty": "medium"
      },
      {
        "title": "Best time to buy and sell stock",
        "url": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
        "difficulty": "easy"
      },
      {
        "title": "Reverse array",
        "url": "https://leetcode.com/problems/reverse-string/",
        "difficulty": "easy"
      },
      {
        "title": "Move zeros to end",
        "url": "https://leetcode.com/problems/move-zeroes/",
        "difficulty": "easy"
      },
      {
        "title": "Remove duplicates from sorted array (two pointers)",
        "url": "https://leetcode.com/problems/remove-duplicates-from-sorted-array/",
        "difficulty": "easy"
      },
      {
        "title": "Two sum",
        "url": "https://leetcode.com/problems/two-sum/",
        "difficulty": "easy"
      },
      {
        "title": "Container with most water",
        "url": "https://leetcode.com/problems/container-with-most-water/",
        "difficulty": "medium"
      },
      {
        "title": "Three sum",
        "url": "https://leetcode.com/problems/3sum/",
        "difficulty": "medium"
      },
      {
        "title": "Trapping rain water",
        "url": "https://leetcode.com/problems/trapping-rain-water/",
        "difficulty": "hard"
      },
      {
        "title": "Merge sorted array",
        "url": "https://leetcode.com/problems/merge-sorted-array/",
        "difficulty": "easy"
      },
      {
        "title": "Sort colors",
        "url": "https://leetcode.com/problems/sort-colors/",
        "difficulty": "medium"
      },
      {
        "title": "Binary search",
        "url": "https://leetcode.com/problems/binary-search/",
        "difficulty": "easy"
      },
      {
        "title": "Find peak element",
        "url": "https://leetcode.com/problems/find-peak-element/",
        "difficulty": "medium"
      },
      {
        "title": "Search in rotated sorted array",
        "url": "https://leetcode.com/problems/search-in-rotated-sorted-array/",
        "difficulty": "medium"
      },
      {
        "title": "Median of two sorted arrays",
        "url": "https://leetcode.com/problems/median-of-two-sorted-arrays/",
        "difficulty": "hard"
      },
      {
        "title": "Spiral matrix",
        "url": "https://leetcode.com/problems/spiral-matrix/",
        "difficulty": "medium"
      },
      {
        "title": "Rotate image",
        "url": "https://leetcode.com/problems/rotate-image/",
        "difficulty": "medium"
      },
      {
        "title": "Set matrix zeroes",
        "url": "https://leetcode.com/problems/set-matrix-zeroes/",
        "difficulty": "medium"
      },
      {
        "title": "Merge intervals",
        "url": "https://leetcode.com/problems/merge-intervals/",
        "difficulty": "medium"
      },
      {
        "title": "Insert interval",
        "url": "https://leetcode.com/problems/insert-interval/",
        "difficulty": "medium"
      },
      {
        "title": "Meeting rooms II",
        "url": "https://leetcode.com/problems/meeting-rooms-ii/",
        "difficulty": "medium"
      },
      {
        "title": "Product of array except self",
        "url": "https://leetcode.com/problems/product-of-array-except-self/",
        "difficulty": "medium"
      },
      {
        "title": "Maximum subarray",
        "url": "https://leetcode.com/problems/maximum-subarray/",
        "difficulty": "medium"
      },
      {
        "title": "Subarray sum equals k",
        "url": "https://leetcode.com/problems/subarray-sum-equals-k/",
        "difficulty": "medium"
      },
      {
        "title": "Max sum subarray of size k",
        "url": "https://www.geeksforgeeks.org/problems/max-sum-subarray-of-size-k--gfg--1/1",
        "difficulty": "easy"
      },
      {
        "title": "Longest substring without repeating characters",
        "url": "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
        "difficulty": "medium"
      },
      {
        "title": "Minimum window substring",
        "url": "https://leetcode.com/problems/minimum-window-substring/",
        "difficulty": "hard"
      },
      {
        "title": "Sliding window maximum",
        "url": "https://leetcode.com/problems/sliding-window-maximum/",
        "difficulty": "hard"
      }
    ]
  },
  {
    "id": "bit-manipulation",
    "topic": "Bit manipulation",
    "topicColor": "#b3b3b3",
    "problems": [
      {
        "title": "Number of 1 bits",
        "url": "https://leetcode.com/problems/number-of-1-bits/",
        "difficulty": "easy"
      },
      {
        "title": "Power of two",
        "url": "https://leetcode.com/problems/power-of-two/",
        "difficulty": "easy"
      },
      {
        "title": "Count of bits (Hamming weight / counting bits)",
        "url": "https://leetcode.com/problems/counting-bits/",
        "difficulty": "easy"
      },
      {
        "title": "Reverse bits",
        "url": "https://leetcode.com/problems/reverse-bits/",
        "difficulty": "easy"
      },
      {
        "title": "Single number",
        "url": "https://leetcode.com/problems/single-number/",
        "difficulty": "easy"
      },
      {
        "title": "Missing number",
        "url": "https://leetcode.com/problems/missing-number/",
        "difficulty": "easy"
      },
      {
        "title": "Single number II",
        "url": "https://leetcode.com/problems/single-number-ii/",
        "difficulty": "medium"
      },
      {
        "title": "Sum of two integers",
        "url": "https://leetcode.com/problems/sum-of-two-integers/",
        "difficulty": "medium"
      },
      {
        "title": "Decode XORed permutation",
        "url": "https://leetcode.com/problems/decode-xored-permutation/",
        "difficulty": "medium"
      },
      {
        "title": "Bitwise AND of numbers range",
        "url": "https://leetcode.com/problems/bitwise-and-of-numbers-range/",
        "difficulty": "medium"
      },
      {
        "title": "Maximum product of word lengths",
        "url": "https://leetcode.com/problems/maximum-product-of-word-lengths/",
        "difficulty": "medium"
      },
      {
        "title": "UTF-8 validation",
        "url": "https://leetcode.com/problems/utf-8-validation/",
        "difficulty": "medium"
      }
    ]
  },
  {
    "id": "hashing",
    "topic": "Hashing",
    "topicColor": "#43a047",
    "problems": [
      {
        "title": "Two sum",
        "url": "https://leetcode.com/problems/two-sum/",
        "difficulty": "easy"
      },
      {
        "title": "Contains duplicate",
        "url": "https://leetcode.com/problems/contains-duplicate/",
        "difficulty": "easy"
      },
      {
        "title": "Valid anagram",
        "url": "https://leetcode.com/problems/valid-anagram/",
        "difficulty": "easy"
      },
      {
        "title": "Group anagrams",
        "url": "https://leetcode.com/problems/group-anagrams/",
        "difficulty": "medium"
      },
      {
        "title": "Subarray sum equals k",
        "url": "https://leetcode.com/problems/subarray-sum-equals-k/",
        "difficulty": "medium"
      },
      {
        "title": "Longest consecutive sequence",
        "url": "https://leetcode.com/problems/longest-consecutive-sequence/",
        "difficulty": "medium"
      },
      {
        "title": "Continuous subarray sum",
        "url": "https://leetcode.com/problems/continuous-subarray-sum/",
        "difficulty": "medium"
      },
      {
        "title": "Design HashMap",
        "url": "https://leetcode.com/problems/design-hashmap/",
        "difficulty": "easy"
      },
      {
        "title": "LRU cache",
        "url": "https://leetcode.com/problems/lru-cache/",
        "difficulty": "medium"
      },
      {
        "title": "LFU cache",
        "url": "https://leetcode.com/problems/lfu-cache/",
        "difficulty": "hard"
      },
      {
        "title": "4Sum II",
        "url": "https://leetcode.com/problems/4sum-ii/",
        "difficulty": "medium"
      },
      {
        "title": "Minimum window substring",
        "url": "https://leetcode.com/problems/minimum-window-substring/",
        "difficulty": "hard"
      },
      {
        "title": "Subarrays with K different integers",
        "url": "https://leetcode.com/problems/subarrays-with-k-different-integers/",
        "difficulty": "hard"
      }
    ]
  },
  {
    "id": "mathematics",
    "topic": "Mathematics",
    "topicColor": "#42a5f5",
    "problems": [
      {
        "title": "Palindrome number",
        "url": "https://leetcode.com/problems/palindrome-number/",
        "difficulty": "easy"
      },
      {
        "title": "Reverse integer",
        "url": "https://leetcode.com/problems/reverse-integer/",
        "difficulty": "medium"
      },
      {
        "title": "Sqrt(x)",
        "url": "https://leetcode.com/problems/sqrtx/",
        "difficulty": "easy"
      },
      {
        "title": "Pow(x, n)",
        "url": "https://leetcode.com/problems/powx-n/",
        "difficulty": "medium"
      },
      {
        "title": "Count primes",
        "url": "https://leetcode.com/problems/count-primes/",
        "difficulty": "medium"
      },
      {
        "title": "Factorial trailing zeroes",
        "url": "https://leetcode.com/problems/factorial-trailing-zeroes/",
        "difficulty": "medium"
      },
      {
        "title": "Pascal's triangle",
        "url": "https://leetcode.com/problems/pascals-triangle/",
        "difficulty": "easy"
      },
      {
        "title": "Unique paths",
        "url": "https://leetcode.com/problems/unique-paths/",
        "difficulty": "medium"
      },
      {
        "title": "Integer to roman",
        "url": "https://leetcode.com/problems/integer-to-roman/",
        "difficulty": "medium"
      },
      {
        "title": "Roman to integer",
        "url": "https://leetcode.com/problems/roman-to-integer/",
        "difficulty": "easy"
      }
    ]
  },
  {
    "id": "strings",
    "topic": "Strings",
    "topicColor": "#ec407a",
    "problems": [
      {
        "title": "Reverse string",
        "url": "https://leetcode.com/problems/reverse-string/",
        "difficulty": "easy"
      },
      {
        "title": "Valid palindrome",
        "url": "https://leetcode.com/problems/valid-palindrome/",
        "difficulty": "easy"
      },
      {
        "title": "First unique character in a string",
        "url": "https://leetcode.com/problems/first-unique-character-in-a-string/",
        "difficulty": "easy"
      },
      {
        "title": "Longest common prefix",
        "url": "https://leetcode.com/problems/longest-common-prefix/",
        "difficulty": "easy"
      },
      {
        "title": "Reverse words in a string",
        "url": "https://leetcode.com/problems/reverse-words-in-a-string/",
        "difficulty": "medium"
      },
      {
        "title": "Valid palindrome II",
        "url": "https://leetcode.com/problems/valid-palindrome-ii/",
        "difficulty": "easy"
      },
      {
        "title": "Longest palindromic substring",
        "url": "https://leetcode.com/problems/longest-palindromic-substring/",
        "difficulty": "medium"
      },
      {
        "title": "Longest substring without repeating characters",
        "url": "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
        "difficulty": "medium"
      },
      {
        "title": "Longest repeating character replacement",
        "url": "https://leetcode.com/problems/longest-repeating-character-replacement/",
        "difficulty": "medium"
      },
      {
        "title": "Minimum window substring",
        "url": "https://leetcode.com/problems/minimum-window-substring/",
        "difficulty": "hard"
      },
      {
        "title": "Valid anagram",
        "url": "https://leetcode.com/problems/valid-anagram/",
        "difficulty": "easy"
      },
      {
        "title": "Group anagrams",
        "url": "https://leetcode.com/problems/group-anagrams/",
        "difficulty": "medium"
      },
      {
        "title": "Word pattern",
        "url": "https://leetcode.com/problems/word-pattern/",
        "difficulty": "easy"
      },
      {
        "title": "Implement strStr()",
        "url": "https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/",
        "difficulty": "easy"
      },
      {
        "title": "Edit distance",
        "url": "https://leetcode.com/problems/edit-distance/",
        "difficulty": "medium"
      },
      {
        "title": "Wildcard matching",
        "url": "https://leetcode.com/problems/wildcard-matching/",
        "difficulty": "hard"
      },
      {
        "title": "String to integer (atoi)",
        "url": "https://leetcode.com/problems/string-to-integer-atoi/",
        "difficulty": "medium"
      },
      {
        "title": "Longest palindromic subsequence",
        "url": "https://leetcode.com/problems/longest-palindromic-subsequence/",
        "difficulty": "medium"
      },
      {
        "title": "Palindrome partitioning",
        "url": "https://leetcode.com/problems/palindrome-partitioning/",
        "difficulty": "medium"
      }
    ]
  },
  {
    "id": "binary-search",
    "topic": "Binary search",
    "topicColor": "#7c4dff",
    "problems": [
      {
        "title": "Binary search",
        "url": "https://leetcode.com/problems/binary-search/",
        "difficulty": "easy"
      },
      {
        "title": "First bad version",
        "url": "https://leetcode.com/problems/first-bad-version/",
        "difficulty": "easy"
      },
      {
        "title": "Search insert position",
        "url": "https://leetcode.com/problems/search-insert-position/",
        "difficulty": "easy"
      },
      {
        "title": "Find minimum in rotated sorted array",
        "url": "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
        "difficulty": "medium"
      },
      {
        "title": "Search in rotated sorted array",
        "url": "https://leetcode.com/problems/search-in-rotated-sorted-array/",
        "difficulty": "medium"
      },
      {
        "title": "Find peak element",
        "url": "https://leetcode.com/problems/find-peak-element/",
        "difficulty": "medium"
      },
      {
        "title": "Find first and last position of element in sorted array",
        "url": "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/",
        "difficulty": "medium"
      },
      {
        "title": "Search a 2D matrix",
        "url": "https://leetcode.com/problems/search-a-2d-matrix/",
        "difficulty": "medium"
      },
      {
        "title": "Kth smallest element in a sorted matrix",
        "url": "https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/",
        "difficulty": "medium"
      },
      {
        "title": "Koko eating bananas",
        "url": "https://leetcode.com/problems/koko-eating-bananas/",
        "difficulty": "medium"
      },
      {
        "title": "Capacity to ship packages within D days",
        "url": "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/",
        "difficulty": "medium"
      },
      {
        "title": "Split array largest sum",
        "url": "https://leetcode.com/problems/split-array-largest-sum/",
        "difficulty": "hard"
      },
      {
        "title": "Book allocation (split array largest sum)",
        "url": "https://leetcode.com/problems/split-array-largest-sum/",
        "difficulty": "hard"
      },
      {
        "title": "Aggressive cows",
        "url": "https://www.geeksforgeeks.org/problems/aggressive-cows--gfg--1/1",
        "difficulty": "hard"
      },
      {
        "title": "Median of two sorted arrays",
        "url": "https://leetcode.com/problems/median-of-two-sorted-arrays/",
        "difficulty": "hard"
      },
      {
        "title": "Minimize max distance to gas station",
        "url": "https://leetcode.com/problems/minimize-max-distance-to-gas-station/",
        "difficulty": "hard"
      }
    ]
  },
  {
    "id": "recursion-backtracking",
    "topic": "Recursion & backtracking",
    "topicColor": "#26c6da",
    "problems": [
      {
        "title": "Factorial",
        "url": "https://www.geeksforgeeks.org/problems/factorial--gfg--1/1",
        "difficulty": "easy"
      },
      {
        "title": "Fibonacci number",
        "url": "https://leetcode.com/problems/fibonacci-number/",
        "difficulty": "easy"
      },
      {
        "title": "Reverse string (recursion)",
        "url": "https://leetcode.com/problems/reverse-string/",
        "difficulty": "easy"
      },
      {
        "title": "Pow(x, n)",
        "url": "https://leetcode.com/problems/powx-n/",
        "difficulty": "medium"
      },
      {
        "title": "Binary search (recursion)",
        "url": "https://leetcode.com/problems/binary-search/",
        "difficulty": "easy"
      },
      {
        "title": "Merge sort",
        "url": "https://www.geeksforgeeks.org/problems/merge-sort--gfg--1/1",
        "difficulty": "medium"
      },
      {
        "title": "Quick sort",
        "url": "https://www.geeksforgeeks.org/problems/quick-sort--gfg--1/1",
        "difficulty": "medium"
      },
      {
        "title": "Subsets",
        "url": "https://leetcode.com/problems/subsets/",
        "difficulty": "medium"
      },
      {
        "title": "Combination sum",
        "url": "https://leetcode.com/problems/combination-sum/",
        "difficulty": "medium"
      },
      {
        "title": "Subsets II",
        "url": "https://leetcode.com/problems/subsets-ii/",
        "difficulty": "medium"
      },
      {
        "title": "Combination sum II",
        "url": "https://leetcode.com/problems/combination-sum-ii/",
        "difficulty": "medium"
      },
      {
        "title": "Letter combinations of a phone number",
        "url": "https://leetcode.com/problems/letter-combinations-of-a-phone-number/",
        "difficulty": "medium"
      },
      {
        "title": "Permutations",
        "url": "https://leetcode.com/problems/permutations/",
        "difficulty": "medium"
      },
      {
        "title": "Generate parentheses",
        "url": "https://leetcode.com/problems/generate-parentheses/",
        "difficulty": "medium"
      },
      {
        "title": "Palindrome partitioning",
        "url": "https://leetcode.com/problems/palindrome-partitioning/",
        "difficulty": "medium"
      },
      {
        "title": "Word search",
        "url": "https://leetcode.com/problems/word-search/",
        "difficulty": "medium"
      },
      {
        "title": "N-Queens",
        "url": "https://leetcode.com/problems/n-queens/",
        "difficulty": "hard"
      },
      {
        "title": "Sudoku solver",
        "url": "https://leetcode.com/problems/sudoku-solver/",
        "difficulty": "hard"
      }
    ]
  },
  {
    "id": "linked-list",
    "topic": "Linked list",
    "topicColor": "#ff9800",
    "problems": [
      {
        "title": "Reverse linked list",
        "url": "https://leetcode.com/problems/reverse-linked-list/",
        "difficulty": "easy"
      },
      {
        "title": "Middle of the linked list",
        "url": "https://leetcode.com/problems/middle-of-the-linked-list/",
        "difficulty": "easy"
      },
      {
        "title": "Delete node in a linked list",
        "url": "https://leetcode.com/problems/delete-node-in-a-linked-list/",
        "difficulty": "medium"
      },
      {
        "title": "Remove Nth node from end of list",
        "url": "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
        "difficulty": "medium"
      },
      {
        "title": "Linked list cycle",
        "url": "https://leetcode.com/problems/linked-list-cycle/",
        "difficulty": "easy"
      },
      {
        "title": "Linked list cycle II",
        "url": "https://leetcode.com/problems/linked-list-cycle-ii/",
        "difficulty": "medium"
      },
      {
        "title": "Find length of loop in linked list",
        "url": "https://www.geeksforgeeks.org/problems/length-of-loop--gfg--1/1",
        "difficulty": "easy"
      },
      {
        "title": "Reverse linked list II",
        "url": "https://leetcode.com/problems/reverse-linked-list-ii/",
        "difficulty": "medium"
      },
      {
        "title": "Reorder list",
        "url": "https://leetcode.com/problems/reorder-list/",
        "difficulty": "medium"
      },
      {
        "title": "Reverse nodes in k-group",
        "url": "https://leetcode.com/problems/reverse-nodes-in-k-group/",
        "difficulty": "hard"
      },
      {
        "title": "Merge two sorted lists",
        "url": "https://leetcode.com/problems/merge-two-sorted-lists/",
        "difficulty": "easy"
      },
      {
        "title": "Partition list",
        "url": "https://leetcode.com/problems/partition-list/",
        "difficulty": "medium"
      },
      {
        "title": "Sort list",
        "url": "https://leetcode.com/problems/sort-list/",
        "difficulty": "medium"
      },
      {
        "title": "Merge k sorted lists",
        "url": "https://leetcode.com/problems/merge-k-sorted-lists/",
        "difficulty": "hard"
      },
      {
        "title": "Intersection of two linked lists",
        "url": "https://leetcode.com/problems/intersection-of-two-linked-lists/",
        "difficulty": "easy"
      },
      {
        "title": "Copy list with random pointer",
        "url": "https://leetcode.com/problems/copy-list-with-random-pointer/",
        "difficulty": "medium"
      },
      {
        "title": "Flatten a multilevel doubly linked list",
        "url": "https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list/",
        "difficulty": "medium"
      }
    ]
  },
  {
    "id": "stacks-queues",
    "topic": "Stacks & queues",
    "topicColor": "#ab47bc",
    "problems": [
      {
        "title": "Implement stack using queues",
        "url": "https://leetcode.com/problems/implement-stack-using-queues/",
        "difficulty": "easy"
      },
      {
        "title": "Implement queue using stacks",
        "url": "https://leetcode.com/problems/implement-queue-using-stacks/",
        "difficulty": "easy"
      },
      {
        "title": "Min stack",
        "url": "https://leetcode.com/problems/min-stack/",
        "difficulty": "medium"
      },
      {
        "title": "Valid parentheses",
        "url": "https://leetcode.com/problems/valid-parentheses/",
        "difficulty": "easy"
      },
      {
        "title": "Backspace string compare",
        "url": "https://leetcode.com/problems/backspace-string-compare/",
        "difficulty": "easy"
      },
      {
        "title": "Remove outermost parentheses",
        "url": "https://leetcode.com/problems/remove-outermost-parentheses/",
        "difficulty": "easy"
      },
      {
        "title": "Next greater element I",
        "url": "https://leetcode.com/problems/next-greater-element-i/",
        "difficulty": "easy"
      },
      {
        "title": "Daily temperatures",
        "url": "https://leetcode.com/problems/daily-temperatures/",
        "difficulty": "medium"
      },
      {
        "title": "Next greater element II",
        "url": "https://leetcode.com/problems/next-greater-element-ii/",
        "difficulty": "medium"
      },
      {
        "title": "Online stock span",
        "url": "https://leetcode.com/problems/online-stock-span/",
        "difficulty": "medium"
      },
      {
        "title": "Sum of subarray minimums",
        "url": "https://leetcode.com/problems/sum-of-subarray-minimums/",
        "difficulty": "medium"
      },
      {
        "title": "Evaluate reverse polish notation",
        "url": "https://leetcode.com/problems/evaluate-reverse-polish-notation/",
        "difficulty": "medium"
      },
      {
        "title": "Decode string",
        "url": "https://leetcode.com/problems/decode-string/",
        "difficulty": "medium"
      },
      {
        "title": "Basic calculator",
        "url": "https://leetcode.com/problems/basic-calculator/",
        "difficulty": "hard"
      },
      {
        "title": "Remove k digits",
        "url": "https://leetcode.com/problems/remove-k-digits/",
        "difficulty": "medium"
      },
      {
        "title": "Largest rectangle in histogram",
        "url": "https://leetcode.com/problems/largest-rectangle-in-histogram/",
        "difficulty": "hard"
      },
      {
        "title": "Trapping rain water",
        "url": "https://leetcode.com/problems/trapping-rain-water/",
        "difficulty": "hard"
      },
      {
        "title": "Maximal rectangle",
        "url": "https://leetcode.com/problems/maximal-rectangle/",
        "difficulty": "hard"
      },
      {
        "title": "Sliding window maximum",
        "url": "https://leetcode.com/problems/sliding-window-maximum/",
        "difficulty": "hard"
      }
    ]
  },
  {
    "id": "binary-trees",
    "topic": "Binary trees",
    "topicColor": "#66bb6a",
    "problems": [
      {
        "title": "Binary tree inorder traversal",
        "url": "https://leetcode.com/problems/binary-tree-inorder-traversal/",
        "difficulty": "easy"
      },
      {
        "title": "Binary tree preorder traversal",
        "url": "https://leetcode.com/problems/binary-tree-preorder-traversal/",
        "difficulty": "easy"
      },
      {
        "title": "Binary tree postorder traversal",
        "url": "https://leetcode.com/problems/binary-tree-postorder-traversal/",
        "difficulty": "easy"
      },
      {
        "title": "Binary tree level order traversal",
        "url": "https://leetcode.com/problems/binary-tree-level-order-traversal/",
        "difficulty": "medium"
      },
      {
        "title": "Binary tree zigzag level order traversal",
        "url": "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/",
        "difficulty": "medium"
      },
      {
        "title": "Vertical order traversal of a binary tree",
        "url": "https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/",
        "difficulty": "hard"
      },
      {
        "title": "Symmetric tree",
        "url": "https://leetcode.com/problems/symmetric-tree/",
        "difficulty": "easy"
      },
      {
        "title": "Invert binary tree",
        "url": "https://leetcode.com/problems/invert-binary-tree/",
        "difficulty": "easy"
      },
      {
        "title": "Maximum depth of binary tree",
        "url": "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
        "difficulty": "easy"
      },
      {
        "title": "Balanced binary tree",
        "url": "https://leetcode.com/problems/balanced-binary-tree/",
        "difficulty": "easy"
      },
      {
        "title": "Diameter of binary tree",
        "url": "https://leetcode.com/problems/diameter-of-binary-tree/",
        "difficulty": "easy"
      },
      {
        "title": "Binary tree right side view",
        "url": "https://leetcode.com/problems/binary-tree-right-side-view/",
        "difficulty": "medium"
      },
      {
        "title": "Bottom view of binary tree",
        "url": "https://www.geeksforgeeks.org/problems/bottom-view-of-binary-tree--gfg--1/1",
        "difficulty": "medium"
      },
      {
        "title": "Top view of binary tree",
        "url": "https://www.geeksforgeeks.org/problems/top-view-of-binary-tree--gfg--1/1",
        "difficulty": "medium"
      },
      {
        "title": "Path sum",
        "url": "https://leetcode.com/problems/path-sum/",
        "difficulty": "easy"
      },
      {
        "title": "Path sum II",
        "url": "https://leetcode.com/problems/path-sum-ii/",
        "difficulty": "medium"
      },
      {
        "title": "Sum root to leaf numbers",
        "url": "https://leetcode.com/problems/sum-root-to-leaf-numbers/",
        "difficulty": "medium"
      },
      {
        "title": "Binary tree maximum path sum",
        "url": "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
        "difficulty": "hard"
      },
      {
        "title": "Search in a binary search tree",
        "url": "https://leetcode.com/problems/search-in-a-binary-search-tree/",
        "difficulty": "easy"
      },
      {
        "title": "Validate binary search tree",
        "url": "https://leetcode.com/problems/validate-binary-search-tree/",
        "difficulty": "medium"
      },
      {
        "title": "Kth smallest element in a BST",
        "url": "https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
        "difficulty": "medium"
      },
      {
        "title": "Lowest common ancestor of a binary search tree",
        "url": "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
        "difficulty": "easy"
      },
      {
        "title": "Flatten binary tree to linked list",
        "url": "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/",
        "difficulty": "medium"
      },
      {
        "title": "Construct binary tree from preorder and postorder traversal",
        "url": "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-postorder-traversal/",
        "difficulty": "medium"
      },
      {
        "title": "Serialize and deserialize binary tree",
        "url": "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
        "difficulty": "hard"
      },
      {
        "title": "Lowest common ancestor of a binary tree",
        "url": "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/",
        "difficulty": "medium"
      },
      {
        "title": "Unique binary search trees",
        "url": "https://leetcode.com/problems/unique-binary-search-trees/",
        "difficulty": "medium"
      },
      {
        "title": "House robber III",
        "url": "https://leetcode.com/problems/house-robber-iii/",
        "difficulty": "medium"
      },
      {
        "title": "All possible full binary trees",
        "url": "https://leetcode.com/problems/all-possible-full-binary-trees/",
        "difficulty": "medium"
      },
      {
        "title": "Binary tree cameras",
        "url": "https://leetcode.com/problems/binary-tree-cameras/",
        "difficulty": "hard"
      }
    ]
  },
  {
    "id": "heaps",
    "topic": "Heaps & priority queues",
    "topicColor": "#ef5350",
    "problems": [
      {
        "title": "Kth largest element in an array",
        "url": "https://leetcode.com/problems/kth-largest-element-in-an-array/",
        "difficulty": "medium"
      },
      {
        "title": "Kth largest element in a stream",
        "url": "https://leetcode.com/problems/kth-largest-element-in-a-stream/",
        "difficulty": "easy"
      },
      {
        "title": "Top K frequent elements",
        "url": "https://leetcode.com/problems/top-k-frequent-elements/",
        "difficulty": "medium"
      },
      {
        "title": "K closest points to origin",
        "url": "https://leetcode.com/problems/k-closest-points-to-origin/",
        "difficulty": "medium"
      },
      {
        "title": "Kth smallest element in a sorted matrix",
        "url": "https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/",
        "difficulty": "medium"
      },
      {
        "title": "Find k pairs with smallest sums",
        "url": "https://leetcode.com/problems/find-k-pairs-with-smallest-sums/",
        "difficulty": "medium"
      },
      {
        "title": "Merge k sorted lists",
        "url": "https://leetcode.com/problems/merge-k-sorted-lists/",
        "difficulty": "hard"
      },
      {
        "title": "Meeting rooms II",
        "url": "https://leetcode.com/problems/meeting-rooms-ii/",
        "difficulty": "medium"
      },
      {
        "title": "Task scheduler",
        "url": "https://leetcode.com/problems/task-scheduler/",
        "difficulty": "medium"
      },
      {
        "title": "Single-threaded CPU",
        "url": "https://leetcode.com/problems/single-threaded-cpu/",
        "difficulty": "medium"
      },
      {
        "title": "Reorganize string",
        "url": "https://leetcode.com/problems/reorganize-string/",
        "difficulty": "medium"
      },
      {
        "title": "Furthest building you can reach",
        "url": "https://leetcode.com/problems/furthest-building-you-can-reach/",
        "difficulty": "medium"
      },
      {
        "title": "Minimum cost to hire k workers",
        "url": "https://leetcode.com/problems/minimum-cost-to-hire-k-workers/",
        "difficulty": "hard"
      },
      {
        "title": "Find median from data stream",
        "url": "https://leetcode.com/problems/find-median-from-data-stream/",
        "difficulty": "hard"
      },
      {
        "title": "Sliding window median",
        "url": "https://leetcode.com/problems/sliding-window-median/",
        "difficulty": "hard"
      },
      {
        "title": "Network delay time",
        "url": "https://leetcode.com/problems/network-delay-time/",
        "difficulty": "medium"
      },
      {
        "title": "Path with minimum effort",
        "url": "https://leetcode.com/problems/path-with-minimum-effort/",
        "difficulty": "medium"
      },
      {
        "title": "Cheapest flights within K stops",
        "url": "https://leetcode.com/problems/cheapest-flights-within-k-stops/",
        "difficulty": "medium"
      },
      {
        "title": "Swim in rising water",
        "url": "https://leetcode.com/problems/swim-in-rising-water/",
        "difficulty": "hard"
      }
    ]
  },
  {
    "id": "graphs",
    "topic": "Graphs",
    "topicColor": "#29b6f6",
    "problems": [
      {
        "title": "Flood fill",
        "url": "https://leetcode.com/problems/flood-fill/",
        "difficulty": "easy"
      },
      {
        "title": "Number of islands",
        "url": "https://leetcode.com/problems/number-of-islands/",
        "difficulty": "medium"
      },
      {
        "title": "Number of connected components in an undirected graph",
        "url": "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/",
        "difficulty": "medium"
      },
      {
        "title": "Clone graph",
        "url": "https://leetcode.com/problems/clone-graph/",
        "difficulty": "medium"
      },
      {
        "title": "Pacific Atlantic water flow",
        "url": "https://leetcode.com/problems/pacific-atlantic-water-flow/",
        "difficulty": "medium"
      },
      {
        "title": "Detect cycle in undirected graph",
        "url": "https://www.geeksforgeeks.org/problems/detect-cycle-in-an-undirected-graph--gfg--1/1",
        "difficulty": "medium"
      },
      {
        "title": "Course schedule",
        "url": "https://leetcode.com/problems/course-schedule/",
        "difficulty": "medium"
      },
      {
        "title": "Detect cycle in directed graph",
        "url": "https://www.geeksforgeeks.org/problems/detect-cycle-in-a-directed-graph--gfg--1/1",
        "difficulty": "medium"
      },
      {
        "title": "Redundant connection",
        "url": "https://leetcode.com/problems/redundant-connection/",
        "difficulty": "medium"
      },
      {
        "title": "Dijkstra algorithm",
        "url": "https://www.geeksforgeeks.org/problems/implementing-dijkstra--gfg--1/1",
        "difficulty": "medium"
      },
      {
        "title": "Rotting oranges",
        "url": "https://leetcode.com/problems/rotting-oranges/",
        "difficulty": "medium"
      },
      {
        "title": "Shortest path in binary matrix",
        "url": "https://leetcode.com/problems/shortest-path-in-binary-matrix/",
        "difficulty": "medium"
      },
      {
        "title": "01 matrix",
        "url": "https://leetcode.com/problems/01-matrix/",
        "difficulty": "medium"
      },
      {
        "title": "Network delay time",
        "url": "https://leetcode.com/problems/network-delay-time/",
        "difficulty": "medium"
      },
      {
        "title": "Path with minimum effort",
        "url": "https://leetcode.com/problems/path-with-minimum-effort/",
        "difficulty": "medium"
      },
      {
        "title": "Cheapest flights within K stops",
        "url": "https://leetcode.com/problems/cheapest-flights-within-k-stops/",
        "difficulty": "medium"
      },
      {
        "title": "Course schedule II",
        "url": "https://leetcode.com/problems/course-schedule-ii/",
        "difficulty": "medium"
      },
      {
        "title": "Find eventual safe states",
        "url": "https://leetcode.com/problems/find-eventual-safe-states/",
        "difficulty": "medium"
      },
      {
        "title": "Alien dictionary",
        "url": "https://leetcode.com/problems/alien-dictionary/",
        "difficulty": "hard"
      },
      {
        "title": "Number of provinces",
        "url": "https://leetcode.com/problems/number-of-provinces/",
        "difficulty": "medium"
      },
      {
        "title": "Graph valid tree",
        "url": "https://leetcode.com/problems/graph-valid-tree/",
        "difficulty": "medium"
      },
      {
        "title": "Accounts merge",
        "url": "https://leetcode.com/problems/accounts-merge/",
        "difficulty": "medium"
      },
      {
        "title": "Number of islands II",
        "url": "https://leetcode.com/problems/number-of-islands-ii/",
        "difficulty": "hard"
      },
      {
        "title": "Min cost to connect all points",
        "url": "https://leetcode.com/problems/min-cost-to-connect-all-points/",
        "difficulty": "medium"
      },
      {
        "title": "Find critical and pseudo-critical edges in MST",
        "url": "https://leetcode.com/problems/find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree/",
        "difficulty": "hard"
      },
      {
        "title": "Is graph bipartite?",
        "url": "https://leetcode.com/problems/is-graph-bipartite/",
        "difficulty": "medium"
      },
      {
        "title": "Possible bipartition",
        "url": "https://leetcode.com/problems/possible-bipartition/",
        "difficulty": "medium"
      },
      {
        "title": "Critical connections in a network",
        "url": "https://leetcode.com/problems/critical-connections-in-a-network/",
        "difficulty": "hard"
      },
      {
        "title": "Longest path in DAG",
        "url": "https://www.geeksforgeeks.org/problems/longest-path-in-directed-acyclic-graph--gfg--1/1",
        "difficulty": "hard"
      },
      {
        "title": "Strongly connected components (Kosaraju)",
        "url": "https://www.geeksforgeeks.org/problems/strongly-connected-component--kosaraju--gfg--1/1",
        "difficulty": "hard"
      }
    ]
  },
  {
    "id": "dynamic-programming",
    "topic": "Dynamic programming",
    "topicColor": "#ffb74d",
    "problems": [
      {
        "title": "Climbing stairs",
        "url": "https://leetcode.com/problems/climbing-stairs/",
        "difficulty": "easy"
      },
      {
        "title": "Min cost climbing stairs",
        "url": "https://leetcode.com/problems/min-cost-climbing-stairs/",
        "difficulty": "easy"
      },
      {
        "title": "House robber",
        "url": "https://leetcode.com/problems/house-robber/",
        "difficulty": "medium"
      },
      {
        "title": "Maximum subarray",
        "url": "https://leetcode.com/problems/maximum-subarray/",
        "difficulty": "medium"
      },
      {
        "title": "House robber II",
        "url": "https://leetcode.com/problems/house-robber-ii/",
        "difficulty": "medium"
      },
      {
        "title": "Jump game",
        "url": "https://leetcode.com/problems/jump-game/",
        "difficulty": "medium"
      },
      {
        "title": "Decode ways",
        "url": "https://leetcode.com/problems/decode-ways/",
        "difficulty": "medium"
      },
      {
        "title": "Word break",
        "url": "https://leetcode.com/problems/word-break/",
        "difficulty": "medium"
      },
      {
        "title": "Unique paths",
        "url": "https://leetcode.com/problems/unique-paths/",
        "difficulty": "medium"
      },
      {
        "title": "Unique paths II",
        "url": "https://leetcode.com/problems/unique-paths-ii/",
        "difficulty": "medium"
      },
      {
        "title": "Minimum path sum",
        "url": "https://leetcode.com/problems/minimum-path-sum/",
        "difficulty": "medium"
      },
      {
        "title": "Triangle",
        "url": "https://leetcode.com/problems/triangle/",
        "difficulty": "medium"
      },
      {
        "title": "Dungeon game",
        "url": "https://leetcode.com/problems/dungeon-game/",
        "difficulty": "hard"
      },
      {
        "title": "Cherry pickup",
        "url": "https://leetcode.com/problems/cherry-pickup/",
        "difficulty": "hard"
      },
      {
        "title": "Coin change II",
        "url": "https://leetcode.com/problems/coin-change-ii/",
        "difficulty": "medium"
      },
      {
        "title": "Coin change",
        "url": "https://leetcode.com/problems/coin-change/",
        "difficulty": "medium"
      },
      {
        "title": "Subset sum",
        "url": "https://www.geeksforgeeks.org/problems/subset-sum-problem--gfg--1/1",
        "difficulty": "medium"
      },
      {
        "title": "Target sum",
        "url": "https://leetcode.com/problems/target-sum/",
        "difficulty": "medium"
      },
      {
        "title": "Partition equal subset sum",
        "url": "https://leetcode.com/problems/partition-equal-subset-sum/",
        "difficulty": "medium"
      },
      {
        "title": "Longest common subsequence",
        "url": "https://leetcode.com/problems/longest-common-subsequence/",
        "difficulty": "medium"
      },
      {
        "title": "Longest palindromic subsequence",
        "url": "https://leetcode.com/problems/longest-palindromic-subsequence/",
        "difficulty": "medium"
      },
      {
        "title": "Longest increasing subsequence",
        "url": "https://leetcode.com/problems/longest-increasing-subsequence/",
        "difficulty": "medium"
      },
      {
        "title": "Largest divisible subset",
        "url": "https://leetcode.com/problems/largest-divisible-subset/",
        "difficulty": "medium"
      },
      {
        "title": "Edit distance",
        "url": "https://leetcode.com/problems/edit-distance/",
        "difficulty": "medium"
      },
      {
        "title": "Distinct subsequences",
        "url": "https://leetcode.com/problems/distinct-subsequences/",
        "difficulty": "hard"
      },
      {
        "title": "Shortest common supersequence",
        "url": "https://www.geeksforgeeks.org/problems/shortest-common-supersequence--gfg--1/1",
        "difficulty": "medium"
      },
      {
        "title": "Minimum cost to cut a stick",
        "url": "https://leetcode.com/problems/minimum-cost-to-cut-a-stick/",
        "difficulty": "hard"
      },
      {
        "title": "Palindrome partitioning II",
        "url": "https://leetcode.com/problems/palindrome-partitioning-ii/",
        "difficulty": "hard"
      },
      {
        "title": "Burst balloons",
        "url": "https://leetcode.com/problems/burst-balloons/",
        "difficulty": "hard"
      },
      {
        "title": "Matrix chain multiplication",
        "url": "https://www.geeksforgeeks.org/problems/matrix-chain-multiplication--gfg--1/1",
        "difficulty": "medium"
      },
      {
        "title": "Unique binary search trees",
        "url": "https://leetcode.com/problems/unique-binary-search-trees/",
        "difficulty": "medium"
      },
      {
        "title": "House robber III",
        "url": "https://leetcode.com/problems/house-robber-iii/",
        "difficulty": "medium"
      },
      {
        "title": "Binary tree maximum path sum",
        "url": "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
        "difficulty": "hard"
      },
      {
        "title": "Binary tree cameras",
        "url": "https://leetcode.com/problems/binary-tree-cameras/",
        "difficulty": "hard"
      },
      {
        "title": "Partition to K equal sum subsets",
        "url": "https://leetcode.com/problems/partition-to-k-equal-sum-subsets/",
        "difficulty": "medium"
      },
      {
        "title": "Shortest path visiting all nodes",
        "url": "https://leetcode.com/problems/shortest-path-visiting-all-nodes/",
        "difficulty": "hard"
      },
      {
        "title": "Travelling salesman problem",
        "url": "https://www.geeksforgeeks.org/problems/travelling-salesman-problem--gfg--1/1",
        "difficulty": "hard"
      },
      {
        "title": "Longest increasing path in a matrix",
        "url": "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/",
        "difficulty": "hard"
      },
      {
        "title": "Wildcard matching",
        "url": "https://leetcode.com/problems/wildcard-matching/",
        "difficulty": "hard"
      },
      {
        "title": "Regular expression matching",
        "url": "https://leetcode.com/problems/regular-expression-matching/",
        "difficulty": "hard"
      },
      {
        "title": "Russian doll envelopes",
        "url": "https://leetcode.com/problems/russian-doll-envelopes/",
        "difficulty": "hard"
      },
      {
        "title": "Maximum profit in job scheduling",
        "url": "https://leetcode.com/problems/maximum-profit-in-job-scheduling/",
        "difficulty": "hard"
      }
    ]
  },
  {
    "id": "tries",
    "topic": "Tries",
    "topicColor": "#9575cd",
    "problems": [
      {
        "title": "Implement trie (prefix tree)",
        "url": "https://leetcode.com/problems/implement-trie-prefix-tree/",
        "difficulty": "medium"
      },
      {
        "title": "Design add and search words data structure",
        "url": "https://leetcode.com/problems/design-add-and-search-words-data-structure/",
        "difficulty": "medium"
      },
      {
        "title": "Replace words",
        "url": "https://leetcode.com/problems/replace-words/",
        "difficulty": "medium"
      },
      {
        "title": "Longest word in dictionary",
        "url": "https://leetcode.com/problems/longest-word-in-dictionary/",
        "difficulty": "easy"
      },
      {
        "title": "Search suggestions system",
        "url": "https://leetcode.com/problems/search-suggestions-system/",
        "difficulty": "medium"
      },
      {
        "title": "Word search II",
        "url": "https://leetcode.com/problems/word-search-ii/",
        "difficulty": "hard"
      },
      {
        "title": "Maximum XOR of two numbers in an array",
        "url": "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/",
        "difficulty": "medium"
      },
      {
        "title": "Palindrome pairs",
        "url": "https://leetcode.com/problems/palindrome-pairs/",
        "difficulty": "hard"
      }
    ]
  },
  {
    "id": "greedy",
    "topic": "Greedy",
    "topicColor": "#26a69a",
    "problems": [
      {
        "title": "Assign cookies",
        "url": "https://leetcode.com/problems/assign-cookies/",
        "difficulty": "easy"
      },
      {
        "title": "Lemonade change",
        "url": "https://leetcode.com/problems/lemonade-change/",
        "difficulty": "easy"
      },
      {
        "title": "Jump game",
        "url": "https://leetcode.com/problems/jump-game/",
        "difficulty": "medium"
      },
      {
        "title": "Non-overlapping intervals",
        "url": "https://leetcode.com/problems/non-overlapping-intervals/",
        "difficulty": "medium"
      },
      {
        "title": "Minimum number of arrows to burst balloons",
        "url": "https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/",
        "difficulty": "medium"
      },
      {
        "title": "Jump game II",
        "url": "https://leetcode.com/problems/jump-game-ii/",
        "difficulty": "medium"
      },
      {
        "title": "Partition labels",
        "url": "https://leetcode.com/problems/partition-labels/",
        "difficulty": "medium"
      },
      {
        "title": "Gas station",
        "url": "https://leetcode.com/problems/gas-station/",
        "difficulty": "medium"
      },
      {
        "title": "Candy",
        "url": "https://leetcode.com/problems/candy/",
        "difficulty": "hard"
      },
      {
        "title": "Task scheduler",
        "url": "https://leetcode.com/problems/task-scheduler/",
        "difficulty": "medium"
      },
      {
        "title": "Queue reconstruction by height",
        "url": "https://leetcode.com/problems/queue-reconstruction-by-height/",
        "difficulty": "hard"
      },
      {
        "title": "Course schedule III",
        "url": "https://leetcode.com/problems/course-schedule-iii/",
        "difficulty": "hard"
      },
      {
        "title": "Maximum profit in job scheduling",
        "url": "https://leetcode.com/problems/maximum-profit-in-job-scheduling/",
        "difficulty": "hard"
      },
      {
        "title": "Minimum refueling stops",
        "url": "https://leetcode.com/problems/minimum-refueling-stops/",
        "difficulty": "hard"
      }
    ]
  }
];
